<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="com.demo.test.DemoTest" duration-ms="21491" started-at="2017-07-31T13:30:33Z" finished-at="2017-07-31T13:30:54Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="21491" started-at="2017-07-31T13:30:33Z" finished-at="2017-07-31T13:30:54Z">
      <class name="com.demo.test.DemoTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.test.DemoTest@5315b42e]" name="setUp" is-config="true" duration-ms="9898" started-at="2017-07-31T16:30:33Z" finished-at="2017-07-31T16:30:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="gotoSeleniumWikiPage()[pri:0, instance:com.demo.test.DemoTest@5315b42e]" name="gotoSeleniumWikiPage" duration-ms="7047" started-at="2017-07-31T16:30:43Z" finished-at="2017-07-31T16:30:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gotoSeleniumWikiPage -->
        <test-method status="FAIL" signature="gotoSeleniumWikiPageFailure()[pri:0, instance:com.demo.test.DemoTest@5315b42e]" name="gotoSeleniumWikiPageFailure" duration-ms="2611" started-at="2017-07-31T16:30:50Z" finished-at="2017-07-31T16:30:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Selenium WebDriver] but found [Selenium]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Selenium WebDriver] but found [Selenium]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.demo.test.DemoTest.gotoSeleniumWikiPageFailure(DemoTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gotoSeleniumWikiPageFailure -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.test.DemoTest@5315b42e]" name="tearDown" is-config="true" duration-ms="1913" started-at="2017-07-31T16:30:52Z" finished-at="2017-07-31T16:30:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.demo.test.DemoTest -->
    </test> <!-- Command line test -->
  </suite> <!-- com.demo.test.DemoTest -->
</testng-results>
